GET http://localhost:3000/

###
POST http://localhost:3000/add
Content-Type: application/json


{
    "Author": "a",
    "title": "how to cook",
    "blogtext": "this is how to cook..."
}


###

GET http://localhost:3000/6244bfeae7418686f03b90bd

###
GET http://localhost:3000/api

###


POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "a",
}

###
POST http://localhost:3000/api/posts
Content-Type: application/json